### ISSUE TITLE
Sim city nes prototype is not working correctly

### ISSUE THREAD

**Issue by joepogo** [0ldsk00l/nestopia#312] opened 2019-03-03 02:43 UTC
Recently a few months ago the prototype for sim city nes was released to the public. Nestopia mostly plays this except the generate map screen is scrambled as well as the in game maps. There are a couple solutions presented in this thread:

https://forums.nesdev.com/viewtopic.php?f=3&t=18532

Both emulators Mister and Nintaco had this same issue. Nintaco was fixed by removing read protection from PRG RAM. 

Mister was fixed by disabling the external attribute mode (palette and the address override) when not in frame. 

The issue could be either one of these or something else.

**Comment by rdanbrook** [comment] 2019-03-05 01:20
Thanks for the info, will look at it when I get the chance.

**Comment by koitsu** [comment] 2019-03-10 11:42
Root cause found: this game is ETROM not EKROM.  The ROM contains a standard NES header (i.e. not NES 2.0, and NestopiaUE AFAIK doesn't support NES 2.0 anyway), so all it knows without an NstDatabase.xml quirk is that it's a MMC5 game with 8KB of PRG-RAM.  It's actually an MMC5 game with 16KB of PRG-RAM.  I'll work on coming up with the NstDatabase.xml quirk for this; should be easy.

**Comment by dragon2snow** [comment] 2019-03-10 13:06
ETROM  Practice mode is working fine?

**Comment by joepogo** [comment] 2019-03-10 19:23
Hey Dragon, correct. Everything else is OK except when you go to practice mode, the map should be blank, so something is still off. Is there an easy way to fix this? There are buildings everywhere.

**Comment by koitsu** [comment] 2019-03-11 09:33
This is more complicated than just a simple XML tweak for PCB type. My latest write-up is here: http://forums.nesdev.com/viewtopic.php?p=235876#p235876

**Comment by rdanbrook** [comment] 2019-03-11 14:20
Thanks everyone involved in trying to figure this out. I've read the thread on the nesdev forums and it does clarify a lot of details. Around Christmas I was trying to figure this out by shifting bits to see if I could do hacks that would make the correct tiles appear and gain a better understanding, but could not find the correct tiles, so clearly it is deeper than that. I'm going to try the XML tweaks later and see if I can get anywhere using those in combination with other techniques.

**Comment by joepogo** [comment] 2019-03-11 15:19
Hey Rdanbrook, I think member NewRisingSun on nesdev forums today might have figured out what we need to do. Sim city on nestopia has problems with the map having tiles when using practice and scenario mode only. The map is fine when starting a new game but these 2 modes exhibit issues. 

Today NewRisingSun was able to replicate the same behavior nestopia is exhibiting by by disabling and enabling the querying of the in-frame status in the EXRAM emulation in Nintendulator.  Although the garbage tiles are different ones than the ones in Nestopia, this is most likely the culprit I would think.

**Comment by joepogo** [comment] 2019-03-18 19:14
Thanks to Dragon2snow the solution has been found here: 

http://forums.nesdev.com/viewtopic.php?f=3&t=18532&start=30

It's literally 2 lines of code that need to be commented out. :) Everything looks great and plays the way it should too. Thanks Dragon!

**Comment by koitsu** [comment] 2019-03-18 19:27
That piece of code is in the PPU emulation core.  The source code he's referencing is in `source/core/NstPpu.cpp` here: https://github.com/0ldsk00l/nestopia/blob/master/source/core/NstPpu.cpp#L3181

Someone familiar with the code will need to explain what `if (hActiveHook) hActiveHook.Execute();` actually does.  I suspect it's a tie-in for executing code at a specific time PPU-cycle-wise, which I would imagine could cause problems with other games.  We need to tread very lightly here and not resort to "quick" solutions.  We're talking about the PPU emulation core here.  @rdanbrook Are you familiar at all with this piece of code?

**Comment by rdanbrook** [comment] 2019-03-18 21:39
It has been a little bit since I familiarized myself with the PPU in depth. I think this may have to do PPU writes while rendering is disabled, which Mega Man 2 actually does during screen transitions (observable in Bubble Man's stage when entering or after dying, background colour will be incorrect if this is not properly emulated), so maybe that could be a point to test. I am unfortunately through the roof with real life stuff until mid April so I can't look deeper at the moment.

**Comment by koitsu** [comment] 2019-03-18 22:29
No problem.  I kind of skimmed the code to try and make heads/tails of it on a general level.  It looks like there are two cases where `hActiveHook.Execute()` is being called:

* https://github.com/0ldsk00l/nestopia/blob/master/source/core/NstPpu.cpp#L2341
* https://github.com/0ldsk00l/nestopia/blob/master/source/core/NstPpu.cpp#L3181

The first is referred to as `HBlankBg`, the 2nd is referred to as `HBlankOff`.  The one that's being proposed to be removed is the latter.

This code conditionally looks at `hActiveHook` then runs `hActiveHook.Execute()`.  For this to be the case, `Ppu::SetHActiveHook` has to be called in advance to set up the hook (assign `hActiveHook` to some piece of code).  Don't confuse any of this with `hBlankHook` or `Ppu::SetHBlankHook` -- they're named so similarly it's easy to mix them up.  I imagine this is done on a per-mapper basis, but let's see.

There are only 2 pieces of code in all of NestopiaUE that call `SetHActiveHook`:

* `source/core/board/NstBoardJyCompany.cpp` -- tons of mappers: https://wiki.nesdev.com/w/index.php?title=J.Y._Company_ASIC
* `source/core/board/NstBoardMmc5.cpp` -- mapper 5

The MMC5 code is here: https://github.com/0ldsk00l/nestopia/blob/master/source/core/board/NstBoardMmc5.cpp#L181

The hook itself is declared here: https://github.com/0ldsk00l/nestopia/blob/master/source/core/board/NstBoardMmc5.cpp#L656

Thus, I'm not sure how to exactly solve this.  The same hook/code in MMC5 is being used in NstPpu.cpp in both places, so I think some additional brains may need to be added to the hook code at line 656 to "short-circuit" it in the `HBlankOff` scenario.

Like I said: changing the PPU behaviour may or may not be the correct solution here, which is what https://github.com/0ldsk00l/nestopia/issues/312#issuecomment-474061776 proposes.  The biggest stumbling block is reverse-engineering this code (excessive OO) and figuring out what the actual/proper behaviour is.  I suspect commenting out said lines could break things in the other mappers.

**Comment by rdanbrook** [comment] 2019-03-18 22:33
I wonder if the real fix is differentiating Sim City from other MMC5 games in the block of code starting at 656. What is it about Sim City that makes it so different?

**Comment by koitsu** [comment] 2019-03-18 22:39
Good question; not sure. This could be a case of a developer doing something with the MMC5 that other games had not. In other words, this could be something "new" that is unknown -- or, alternately, it could be something known that just has never been emulated correctly before (I suspect this).  Other emulators with MMC5 do get this correct (at least Mesen), and MMC5 happens to be one of the most painful mappers there is to emulate and to code for.  I wonder if asking Sour (Mesen author) would be of benefit, since he may be able to make heads/tails of the code here.

**Comment by joepogo** [comment] 2019-03-18 22:48
Just ran a quick test of Megaman 2 with the new code to see what would happen. Nothing changed, i attempted dying in bubble man's stage and also played through the end of it. There was nothing negatively impacted. Everything looks good still.

**Comment by joepogo** [comment] 2019-03-18 22:56
Also, re-reading what NewRisingSun said in the thread about toggling the disabling and enabling of the querying of the in-frame status in the EXRAM emulation. it's entirely possible that at one time it was assumed that MMC5 needed that code or it was previously thought to be accurate. Much like the other issue i started about not ignoring the upper bits. It might have been previously thought to be correct, but actually is not.

**Comment by koitsu** [comment] 2019-03-18 22:56
> Just ran a quick test of Megaman 2 with the new code to see what would happen. Nothing changed, i attempted dying in bubble man's stage and also played through the end of it. There was nothing negatively impacted. Everything looks good still.

I suspect rdanbrook was thinking of `HBlankBg` here (as said, it's very easy to mix up these two pieces of code because they're named similarly and look similar).  My point about this change breaking the J.Y. Company mappers stands (and that relates to very unique behaviour pertaining to PPU reading and IRQ generation): see https://github.com/0ldsk00l/nestopia/blob/master/source/core/board/NstBoardJyCompany.cpp#L463 for details.  https://wiki.nesdev.com/w/index.php?title=J.Y._Company_ASIC#IRQ_Mode_Select_.28.24C001.29 also describes this company's absolutely crazy IRQ generation model.

**Comment by joepogo** [comment] 2019-03-18 23:01
Sure, i just wanted to run a quick and dirty test just to see. Is disabling that hook in the mmc5 code pretty much what NewRisingSun was talking about? I might run a test with Sim City disabling that hook in MMC5.cpp and re-activating the ppu code that was commented out.

**Comment by koitsu** [comment] 2019-03-18 23:15
To answer your question directly (and I assume you are referring to this http://forums.nesdev.com/viewtopic.php?p=235880#p235880 ): I do not know.

Please re-read https://github.com/0ldsk00l/nestopia/issues/312#issuecomment-474126005 specifically the first 3 paragraphs.  In other words: the same piece of code (the `hActiveHook`) is being called in two completely different pieces of the PPU emulation core.  If you remove/comment out line 181 in the MMC5 code, it's going to affect more than what you think.  And again, if you do it and it works, all that means is "it works for this one game", it could mean you've broken other MMC5 games.

All I see being done so far on this are short, terse, one-line responses/answers.  What matters is someone actually digging *deep* -- and I do mean deep -- into the code and REALLY figuring out what needs to be changed properly.  There are several nuances involved, and it really requires someone who is familiar with the code.  Nothing about MMC5 is easy.  I feel strongly that the proposed "remove this line from NstPpu.cpp" is the wrong way to go about this.

**Comment by joepogo** [comment] 2019-03-18 23:24
Yea, i totally understand what you are saying Koitsu. I'm certainly not approaching this as throw some shit and see what sticks. I'm just merely experimenting here and there with pieces of the MMC5 code to see if i can help touch on the REAL issue is and document it here. Nothing more, nothing less. My main concern was trying out what NewRisingSun said just to see if what he is doing will help here and fix the issue. 

Obviously,  Dragon2snow knows way more about nestopia code than i ever will, i would like his input on why he thinks this is the viable solution to this and how he came to this conclusion. He is very good with nestopia when he used to maintain PLUS!

**Comment by dragon2snow** [comment] 2019-03-19 03:02
我只是快速找到原因，要想解决这个问题，大家去努力

**Comment by rdanbrook** [comment] 2019-03-19 03:05
@dragon2snow sí, necesitamos trabajar muy duro!

**Comment by dragon2snow** [comment] 2019-03-19 03:05
我只是快速找到原因，要想解决这个问题，大家去努力.
所以我的方案都是错的，不用理会

**Comment by koitsu** [comment] 2019-03-19 03:36
He says "I came up with a quick fix, but to actually solve it more detailed work will be required by everyone. Don't bother with my quick fix."

**Comment by joepogo** [comment] 2019-03-19 12:59
I just wanted to document my code experimentation findings here if it helps in any way:

First I commented out line 181 in mmc5.cpp and uncommented the 2 lines ppu.cpp and it's a no go, the graphics are scrambled everywhere. so line 181 is surely needed. This was only a test, mind you. 

I then went and commented out the hook line on 656 and removed that and Uncommented out the ppu line again. Same result as the test above. Scrambled graphics. All the lines are needed from both tests. 

I then decided I would go on and test ALL the J.Y company games I could find with the ppu code commented out curious as to what I could find that might be broken, playing through a level, dying, resetting, anything I could think of to try to trigger an issue and I could find NO games with any issues. This was with games and multiple mappers,  mapper 90, mike Tysons's punch out, mapper 209, mapper 211, and mapper 35. I could find nothing with any issues. 

I am not saying this is the final solution nor do I think it is, but I am saying I am not sure 100 percent what that code in ppu was/is needed. So far, I am finding nothing. Just wanted to get this here for those who might try to duplicate the effort, as I went ahead and rounded up as many J.Y Asic games I could find. I'll keep digging as I would like to know what it effects. 

Then I decided to do some further testing with the code commented out in ppu, the 2 hblank lines.

**Comment by joepogo** [comment] 2019-03-19 13:01
I just wanted to document my code experimentation findings here if it helps in any way:

First I commented out line 181 in mmc5.cpp and uncommented the 2 lines ppu.cpp and it's a no go, the graphics are scrambled everywhere. so line 181 is surely needed. This was only a test, mind you.

I then went and commented out the hook line on 656 and removed that and Uncommented out the ppu line again. Same result as the test above. Scrambled graphics. All the lines are needed from both tests.

I then decided I would go on and test ALL the J.Y company games I could find with the ppu code commented out curious as to what I could find that might be broken, playing through a level, dying, resetting, anything I could think of to try to trigger an issue and I could find NO games with any issues. This was with games and multiple mappers, mapper 90, mike Tysons's punch out, mapper 209, mapper 211, and mapper 35. I could find nothing with any issues.

I am not saying this is the final solution nor do I think it is, but I am saying I am not sure 100 percent what that code in ppu was/is needed. So far, I am finding nothing. Just wanted to get this here for those who might try to duplicate the effort, as I went ahead and rounded up as many J.Y Asic games I could find. I'll keep digging as I would like to know what it effects.

**Comment by dragon2snow** [comment] 2019-03-20 04:37
事实上，注掉的代码，并非PPU代码，而是作为hook使用的额外代码。即PPU外的代码。
如果在没有找到最好的解决方案之前就像我一样，我定义mapper 5.15为不执行那两执行代码的mapper，增加新的hook

**Comment by dragon2snow** [comment] 2019-03-20 04:39
所有模拟器都是恰好可以执行某个游戏，而并非真正的模拟仿真精确。包括mame.

**Comment by joepogo** [comment] 2019-03-20 12:44
所以基本上, 它是可以评论出的钩子, 因为 ppu 实际上没有使用该钩子？但也许有一个更有效的方法来做到这一点比评论出两行？这很奇怪, 如果你评论相同的钩子 mmc5. pp, 你会搞砸图形。如果你在 ppu 做, 那么一切都很好。:P

**Comment by rdanbrook** [comment] 2020-12-12 15:36
Fixed in the latest revision.

**Closed by rdanbrook** 2020-12-12 15:36 UTC
